Repository cyfronet-fid/eosc-search-service, pull requests merged in 2022-11, with the labels that each got.

#318 feat: add data sources
  backend/app/routes/web/user_actions.py
  ui/apps/ui/src/app/collections/data/all/adapter.data.ts
  ui/apps/ui/src/app/collections/data/data-sources/adapter.data.ts
  ui/apps/ui/src/app/collections/data/data-sources/data-source.model.ts
  ui/apps/ui/src/app/collections/data/data-sources/filters.data.ts
  ui/apps/ui/src/app/collections/data/data-sources/nav-config.data.ts
  ui/apps/ui/src/app/collections/data/data-sources/search-metadata.data.ts
  ui/apps/ui/src/app/collections/data/index.ts
  ui/apps/ui/src/app/pages/trainings-page/training-detail-page.component.html
Labels: javascript

#335 fix: datasource redirection
  ui/apps/ui/src/app/collections/data/all/adapter.data.ts
  ui/apps/ui/src/app/collections/data/data-sources/adapter.data.ts
Labels: bug

#334 feat: adjust research steps
  transform/all_collection/spark/transformations/commons.py
Labels: data
