Repository cyfronet-fid/eosc-search-service, pull requests merged in 2023-06, with the labels that each got.

#612 feat: #535 include bundles in the search service front
  backend/app/routes/web/search.py
  backend/app/routes/web/user_actions.py
  ui/apps/ui/src/app/collections/data/all/adapter.data.ts
  ui/apps/ui/src/app/collections/data/bundles/adapter.data.ts
  ui/apps/ui/src/app/collections/data/bundles/bundle.model.ts
  ui/apps/ui/src/app/collections/data/bundles/excluded.data.ts
  ui/apps/ui/src/app/collections/data/bundles/filters.data.ts
  ui/apps/ui/src/app/collections/data/bundles/nav-config.data.ts
  ui/apps/ui/src/app/collections/data/bundles/search-metadata.data.ts
  ui/apps/ui/src/app/collections/data/index.ts
  ui/apps/ui/src/app/collections/data/software/excluded.data.ts
  ui/apps/ui/src/app/collections/data/validators.ts
  ui/apps/ui/src/app/collections/repositories/types.ts
  ui/apps/ui/src/app/components/results-with-pagination/result.component.ts
  ui/apps/ui/src/app/components/results-with-pagination/results-with-pagination.component.ts
  ui/apps/ui/src/app/layouts/content-box/content-box.component.ts
  ui/apps/ui/src/app/layouts/content-box/content-box.module.ts
  ui/apps/ui/src/assets/bundle_service.svg
  ui/apps/ui/src/assets/top-icon-10.png
  ui/apps/ui/src/styles.scss
Labels: develop

#643 fix: #641 autocomplete urls broken
  ui/apps/ui/src/app/collections/data/all/adapter.data.ts
  ui/apps/ui/src/app/collections/data/bundles/adapter.data.ts
Labels: bug

#647 fix: #646 fix permitted ig to g
  backend/app/routes/web/user_actions.py
  ui/apps/ui/src/app/collections/data/all/adapter.data.ts
  ui/apps/ui/src/app/components/search-input/search-input.component.ts
Labels: bug

#653 fix: #652 new bundles icon and name
  ui/apps/ui/src/app/collections/data/all/adapter.data.ts
  ui/apps/ui/src/app/collections/data/bundles/adapter.data.ts
  ui/apps/ui/src/app/collections/data/bundles/nav-config.data.ts
  ui/apps/ui/src/app/collections/services/redirect.service.ts
  ui/apps/ui/src/app/components/filters/filter-multiselect/checkboxes-tree.component.ts
  ui/apps/ui/src/app/components/recommendations/recommendations.component.html
  ui/apps/ui/src/app/components/results-with-pagination/result.component.ts
  ui/apps/ui/src/app/components/search-input/search-input.component.ts
  ui/apps/ui/src/app/dictionary/dictionaryType.ts
  ui/apps/ui/src/app/dictionary/translateDictionaryValue.ts
  ui/apps/ui/src/assets/top-icon-10.png
  ui/apps/ui/src/styles.scss
Labels: develop

#657 fix: #652 icon
  ui/apps/ui/src/assets/top-icon-10.png
Labels: blocked

#661 fix: #658 bundle
  ui/apps/ui/src/app/dictionary/translateDictionaryValue.ts
  ui/apps/ui/src/app/pages/search-page/search-page.component.ts
Labels: enhancement

#613 feat: [#542] Forward user action details to other services
  backend/Pipfile.lock
  backend/app/dependencies/user_actions.py
  backend/app/routes/web/user_actions.py
  backend/tests/app/routes/test_user_actions.py
Labels: user actions
