Repository cyfronet-fid/eosc-search-service, pull requests merged in 2024-03, with the labels that each got.

#1270 feat: [#931] JMS subscriber
  transform/.env.template
  transform/Pipfile
  transform/Pipfile.lock
  transform/README.md
  transform/app/api/routes/solr/create_aliases.py
  transform/app/api/routes/solr/create_collections.py
  transform/app/api/routes/solr/delete_collections.py
  transform/app/api/routes/transform/batch.py
  transform/app/jms/__init__.py
  transform/app/jms/connector.py
  transform/app/jms/subscription.py
  transform/app/server.py
  transform/app/services/solr/delete.py
  transform/app/services/solr/utils.py
  transform/app/services/solr/validate.py
  transform/app/settings.py
  transform/app/tasks/delete_data_by_id.py
  transform/app/transform/utils/validate.py
  transform/app/validations/__init__.py
  transform/app/validations/other.py
  transform/app/worker.py
  transform/docker-compose.yml
Labels: enhancement, data, transformer

#1276 fix: Fix live update
  transform/app/jms/__init__.py
  transform/app/jms/connector.py
  transform/app/jms/start_jms.py
  transform/app/jms/subscription.py
  transform/app/server.py
  transform/app/transform/transformers/guideline.py
  transform/docker-compose.yml
Labels: data, transformer

#1288 fix: nullable persistent ids in data sources
  transform/app/transform/transformers/base/marketplace.py
Labels: bug, data

#1289 feat: [#1275] enhance live update
  transform/app/services/jms/connector.py
  transform/app/services/solr/validate.py
  transform/app/transform/live_update/training_ig.py
Labels: Sprint goal, transformer

#1291 debug: debug solr url
  transform/app/services/solr/validate.py
Labels: bug
