Repository cyfronet-fid/eosc-search-service, pull requests merged in 2024-02, with the labels that each got.

#1194 feat: [#1191] Add project and organisation to the solr endpoints
  transform/app/api/routes/solr/create_collections.py
  transform/app/services/mp_pc/data.py
  transform/app/services/solr/refresh.py
  transform/app/settings.py
  transform/app/tasks/batch.py
  transform/app/tasks/create_collections.py
Labels: transformer

#1208 fix: [#1200] auto suggestion
  backend/app/consts.py
  backend/tests/app/routes/test_suggestions.py
Labels: bug

#1217 Add new scientific domains to mapping (before transform service)
  transform/mappings/scientific_domain.py
Labels: data, transformer

#1218 Add new scientific domains to mapping (development)
  transform/app/transform/mappings/scientific_doamin.py
Labels: data, transformer

#1224 fix: fix catalogues
  solr/config/configsets/catalogue_v101/managed-schema
  transform/app/transform/schemas/output/catalogue.py
  transform/app/transform/transformers/catalogue.py
Labels: data, transformer

#1247 fix: [#1213] add resource type mapping
  transform/app/transform/transformers/training.py
Labels: bug, transformer

#1252 fix: [#1212] training scientific domain
  transform/app/api/routes/solr/__init__.py
  transform/app/api/routes/solr/create_aliases.py
  transform/app/api/routes/solr/create_collections.py
  transform/app/api/routes/solr/delete_collections.py
  transform/app/api/routes/transform/__init__.py
  transform/app/api/routes/transform/batch.py
  transform/app/api/routes/transform/full.py
  transform/app/main.py
  transform/app/services/s3/connect.py
  transform/app/services/spark/config.py
  transform/app/settings.py
  transform/app/transform/mappings/scientific_doamin.py
  transform/app/transform/schemas/input/__init__.py
  transform/app/transform/schemas/output/__init__.py
  transform/app/transform/transformers/bundle.py
  transform/app/transform/transformers/catalogue.py
  transform/app/transform/transformers/guideline.py
  transform/app/transform/transformers/offer.py
  transform/app/transform/transformers/project.py
  transform/app/transform/transformers/training.py
Labels: bug, transformer
