Repository cyfronet-fid/eosc-search-service, pull requests merged in 2024-08, with the labels that each got.

#1350 feat: add Sentry integration
  README.md
  backend/Pipfile
  backend/Pipfile.lock
  backend/app/server.py
  backend/app/settings.py
Labels: enhancement

#1364 feat: [#1353] input oag schemas
  transform/docs/schemas/schemas.common.oag.rst
  transform/docs/schemas/schemas.common.rst
  transform/schemas/common/oag/__init__.py
  transform/schemas/common/oag/affiliation.py
  transform/schemas/common/oag/article_processing_charge.py
  transform/schemas/common/oag/author.py
  transform/schemas/common/oag/best_access_right.py
  transform/schemas/common/oag/container.py
  transform/schemas/common/oag/context.py
  transform/schemas/common/oag/country.py
  transform/schemas/common/oag/eosc_if.py
  transform/schemas/common/oag/funder.py
  transform/schemas/common/oag/geolocation.py
  transform/schemas/common/oag/indicator.py
  transform/schemas/common/oag/instance.py
  transform/schemas/common/oag/key_value_model.py
  transform/schemas/common/oag/language.py
  transform/schemas/common/oag/pid.py
  transform/schemas/common/oag/project.py
  transform/schemas/common/oag/provenance.py
  transform/schemas/common/oag/relation.py
  transform/schemas/common/oag/subject.py
  transform/schemas/input/dataset.py
  transform/schemas/input/organisation.py
  transform/schemas/input/other_rp.py
  transform/schemas/input/publication.py
  transform/schemas/input/software.py
  transform/schemas/old/input/dataset.py
  transform/schemas/old/input/other_rp.py
  transform/schemas/old/input/publication.py
  transform/schemas/old/input/software.py
Labels: transformer

#1365 feat: [#1358] add db oag schemas
  transform/schemas/db/dataset.py
  transform/schemas/db/other_rp.py
  transform/schemas/db/publication.py
  transform/schemas/db/software.py
Labels: data, transformer
