Repository cyfronet-fid/eosc-search-service, pull requests merged in 2024-09, with the labels that each got.

#1386 feat: [#1360] readthedocs configuration
  .readthedocs.yaml
Labels: documentation

#1388 fix: [#1360] fix readthedocs documentation
  .readthedocs.yaml
  transform/docs/requirements.txt
  transform/schemas/db/bundle.py
  transform/schemas/db/catalogue.py
  transform/schemas/db/data_source.py
  transform/schemas/db/dataset.py
  transform/schemas/db/guideline.py
  transform/schemas/db/offer.py
  transform/schemas/db/organisation.py
  transform/schemas/db/other_rp.py
  transform/schemas/db/project.py
  transform/schemas/db/provider.py
  transform/schemas/db/publication.py
  transform/schemas/db/service.py
  transform/schemas/db/software.py
  transform/schemas/db/training.py
  transform/schemas/se/bundle.py
  transform/schemas/se/catalogue.py
  transform/schemas/se/data_source.py
  transform/schemas/se/dataset.py
  transform/schemas/se/guideline.py
  transform/schemas/se/offer.py
  transform/schemas/se/organisation.py
  transform/schemas/se/other_rp.py
  transform/schemas/se/project.py
  transform/schemas/se/provider.py
  transform/schemas/se/publication.py
  transform/schemas/se/service.py
  transform/schemas/se/software.py
  transform/schemas/se/training.py
Labels: documentation, transformer

#1400 feat: [#1361] update readme
  transform/README.md
  transform/README.rst
Labels: documentation

#1410 chore: pl eosc variables in settings
  transform/app/settings.py
Labels: transformer

#1416 fix: [#1408] knowledge hub sandbox link
  README.md
  backend/app/settings.py
  backend/tests/app/routes/test_configuration.py
Labels: bug

#1430 refactor: [#1429] redirect, logo, order urls
  ui/apps/ui/src/app/collections/data/all/adapter.data.ts
  ui/apps/ui/src/app/collections/data/bundles/adapter.data.ts
  ui/apps/ui/src/app/collections/data/catalogues/adapter.data.ts
  ui/apps/ui/src/app/collections/data/data-sources/adapter.data.ts
  ui/apps/ui/src/app/collections/data/datasets/adapter.data.ts
  ui/apps/ui/src/app/collections/data/guidelines/adapter.data.ts
  ui/apps/ui/src/app/collections/data/organisations/adapter.data.ts
  ui/apps/ui/src/app/collections/data/other-resources-products/adapter.data.ts
  ui/apps/ui/src/app/collections/data/projects/adapter.data.ts
  ui/apps/ui/src/app/collections/data/providers/adapter.data.ts
  ui/apps/ui/src/app/collections/data/publications/adapter.data.ts
  ui/apps/ui/src/app/collections/data/services/adapter.data.ts
  ui/apps/ui/src/app/collections/data/software/adapter.data.ts
  ui/apps/ui/src/app/collections/data/trainings/adapter.data.ts
  ui/apps/ui/src/app/collections/filters-serializers/utils.ts
  ui/apps/ui/src/app/collections/repositories/types.ts
  ui/apps/ui/src/app/components/recommendations/recommendations.component.html
  ui/apps/ui/src/app/components/results-with-pagination/result.component.html
  ui/apps/ui/src/app/components/results-with-pagination/result.component.ts
  ui/apps/ui/src/app/components/results-with-pagination/results-with-pagination.component.html
  ui/apps/ui/src/app/components/search-input/search-input.component.html
  ui/apps/ui/src/app/layouts/ig-services-card/ig-services-detail-card.component.html
  ui/apps/ui/src/app/layouts/ig-services-card/ig-services-detail-card.component.ts
Labels: refactor, pl-eosc

#1433 fix: [#1429] fix redirect to offers for data sources
  ui/apps/ui/src/app/collections/data/data-sources/adapter.data.ts
Labels: pl-eosc

#1402 feat: [#1401] load data from cloud (s3)
  transform/app/api/schemas/transform/dump.py
  transform/app/mappings/mappings.py
  transform/app/services/celery/task.py
  transform/app/services/celery/task_statuses.py
  transform/app/services/s3/connect.py
  transform/app/services/s3/get_s3_paths.py
  transform/app/services/s3/utils.py
  transform/app/services/s3/validate.py
  transform/app/settings.py
  transform/app/tasks/solr/create_aliases.py
  transform/app/tasks/solr/create_collections.py
  transform/app/tasks/solr/delete_collections.py
  transform/app/tasks/solr/delete_data_by_id.py
  transform/app/tasks/transform/dump/load.py
  transform/app/tasks/transform/dump/process.py
  transform/app/tasks/transform/dump/validate.py
  transform/app/tasks/utils/s3_paths.py
  transform/app/transform/transformers/training.py
  transform/app/transform/utils/common.py
  transform/app/worker.py
  transform/docker-compose.yml
  transform/docs/conf.py
Labels: data, transformer

#1427 feat: landing page in RDS
  ui/apps/ui/src/app/app.routing.module.ts
  ui/apps/ui/src/app/pages/landing-page/landing-page.component.html
  ui/apps/ui/src/app/pages/landing-page/landing-page.component.ts
  ui/apps/ui/src/assets/eoscpl-footer-bg.svg
  ui/apps/ui/src/assets/eoscpl-footer-logo.svg
  ui/apps/ui/src/assets/eoscpl-logo.svg
  ui/apps/ui/src/assets/eoscpl-pic-01.jpg
  ui/apps/ui/src/assets/eoscpl-pic-02.jpg
  ui/apps/ui/src/assets/initiative-01.jpg
  ui/apps/ui/src/assets/initiative-02.jpg
  ui/apps/ui/src/assets/initiative-03.jpg
  ui/apps/ui/src/assets/partner-placeholder.png
  ui/apps/ui/src/assets/service-placeholder.png
  ui/apps/ui/src/eoscpl-topmap.jpg
  ui/apps/ui/src/icon-right-arrow-hover.svg
  ui/apps/ui/src/icon-right-arrow.svg
  ui/apps/ui/src/qa-bg.jpg
  ui/apps/ui/src/scss/landing.scss
Labels: enhancement, refactor

#1436 fix: [#1428] fix rodbuk redirections
  ui/apps/ui/src/app/collections/data/all/adapter.data.ts
  ui/apps/ui/src/app/collections/data/index.ts
  ui/apps/ui/src/app/collections/pl-data/all/adapter.data.ts
  ui/apps/ui/src/app/collections/pl-data/datasets/adapter.data.ts
Labels: bug

#1443 feat: [#1438] mp redirects
  backend/app/routes/web/configuration.py
  backend/app/schemas/configuration_response.py
  backend/app/settings.py
  backend/tests/app/routes/test_configuration.py
  ui/apps/ui/src/app/collections/data/all/adapter.data.ts
  ui/apps/ui/src/app/collections/data/bundles/adapter.data.ts
  ui/apps/ui/src/app/collections/data/catalogues/adapter.data.ts
  ui/apps/ui/src/app/collections/data/data-sources/adapter.data.ts
  ui/apps/ui/src/app/collections/data/index.ts
  ui/apps/ui/src/app/collections/data/providers/adapter.data.ts
  ui/apps/ui/src/app/collections/data/services/adapter.data.ts
  ui/apps/ui/src/app/collections/pl-data/all/adapter.data.ts
  ui/apps/ui/src/app/collections/pl-data/data-sources/adapter.data.ts
  ui/apps/ui/src/app/collections/pl-data/providers/adapter.data.ts
  ui/apps/ui/src/app/collections/pl-data/services/adapter.data.ts
  ui/apps/ui/src/app/components/results-with-pagination/result-ui-controls/pin.component.ts
  ui/apps/ui/src/app/components/results-with-pagination/result.component.ts
  ui/apps/ui/src/app/components/results-with-pagination/results-with-pagination.component.ts
  ui/apps/ui/src/app/layouts/ig-services-card/ig-services-card.component.ts
  ui/apps/ui/src/app/layouts/ig-services-card/ig-services-detail-card.component.ts
  ui/apps/ui/src/app/pages/guidelines-page/guideline-detail-page.component.ts
  ui/apps/ui/src/app/pages/search-page/search-page.component.ts
  ui/apps/ui/src/app/services/config.service.ts
Labels: enhancement

#1446 feat: explore, mp default addresses
  backend/app/settings.py
  backend/tests/app/routes/test_configuration.py
Labels: beyond
